- filename: DBLP.bib
  search_type: FEED
  source_name: MIS Quarterly
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: SCOPE venue_key='journals/misq' AND journal_abbreviated='MIS Q.'
  comment: ''